name: cv_term_project
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- jupyterlab
- ipywidgets
- tqdm
- numpy
- matplotlib
- scikit-learn
- nodejs
- pip
- opencv
- pandas
- pillow
- kaggle
- ultralytics
- gdown
- PyYAML